version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: todo-database-dev
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: todo-backend-dev
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: todoapp
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - todo-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo-frontend-dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    command: npm start

volumes:
  postgres_data_dev:

networks:
  todo-network:
    driver: bridge
